server.port=3000
spring.application.name=cartel-auth-server
server.error.include-message=always

spring.profiles.active=prod


#---
spring.config.activate.on-profile=local

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27018
spring.data.mongodb.database=cartel-user-database

de.flapdoodle.mongodb.embedded.version=7.0.14
de.flapdoodle.mongodb.embedded.databaseDir=${user.dir}/data/mongodb


#---
spring.config.activate.on-profile=prod

spring.autoconfigure.exclude=de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration

spring.data.mongodb.uri=mongodb+srv://jimbo_db_user:${MONGODB_PASSWORD}@cartel-cluster.rhnc2gc.mongodb.net/cartel-user-database?appName=cartel-cluster